apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
      color: green
  template:
    metadata:
      labels:
        app: hello-world
        color: green
    spec:
      containers:
        - name: hello-world
          image: httpd
          ports:
            - containerPort: 80